### ISSUE TITLE
Overwrite function on sample save.

### ISSUE THREAD

**Issue by bhalonen** [relinc/SurePulseDataProcessor#17]
Luke wants an overwrite button here.
![image](https://user-images.githubusercontent.com/7853544/32520468-1f1cf5ca-c3de-11e7-8973-0958ae8efeb1.png)

**Comment by bhalonen** [comment]
@markhalonen Here is a simple video explaining the feature request. https://youtu.be/CMdEFqdg1Sw

**Comment by markhalonen** [comment]
Ok, so how this works is it needs to know which folder to save the sample into. In the video, no folder is selected. Should it then be saved into the root-level folder? aka "Sample Data"? I think it's almost a feature to require users to organize their samples into folders instead of allowing them to make one massive list

If they select a folder and there's already an existing sample, then it will block them. The required steps then are to delete the existing sample and save. I will add an overwrite button to this dialog:
![image](https://user-images.githubusercontent.com/7853605/32693394-65e64426-c6f8-11e7-9370-1995af35eae0.png)
